APP:
  Name: dbeye
  LogPath: /tmp
  LogLevel: INFO
  Development: "true"
Server:
  RunMode: debug
  HTTPPort: 1989
  ReadTimeout: 180
  WriteTimeout: 60
MySQL:
  Host: 192.168.10.53
  Username: root
  Password: An@uanD1
  Port: 3306
  DBName: dbeye
JWT:
  JwtSecret: geek
  JwtExpire: 82800
  JwtIssuer: geek

