APP:
  Name: dbeye
  LogPath: /tmp
  LogLevel: INFO
  Development: "true"
Server:
  RunMode: debug
  HTTPPort: 8973
  ReadTimeout: 180
  WriteTimeout: 60
MySQL:
  Host: 192.168.101.153
  Username: root
  Password: root
  Port: 3306
  DBName: gateway
JWT:
  JwtSecret: geek
  JwtExpire: 82800
  JwtIssuer: geek

